#ifndef __GAME_ENUM__ 
#define __GAME_ENUM__ 

#define BIT64(n) (1ULL << (n))

#define SKILL_RANGE_TOOL (Cell){SKILL_TOOL_AXE, SKILL_TOOL_PICK}
#define SKILL_RANGE_WEAP (Cell){SKILL_WEAP_SIMP, SKILL_WEAP_NONE}

typedef enum {
  MAG_NONE = -1,
  MAG_MINOR,
  MAG_MODEST,
  MAG_NOMINAL,
  MAG_SIGNIF,
  MAG_DONE
}Magnitude;

typedef enum {
    DATA_NONE,
    DATA_INT,
    DATA_FLOAT,
    DATA_BOOL,
    DATA_PTR,
    DATA_ENTITY,
    DATA_CELL,
    DATA_STRING
} DataType;

typedef enum{
  STEP_NONE = -1,
  STEP_ACTION,
  STEP_TURN,
  STEP_FRAME,
  STEP_FIXED,
  STEP_IGM,//IN GAME MINUTE
  STEP_IGH,//IN GAME HOUR
  STEP_IGD,// IN GAME DAY
  STEP_DONE
}StepType;

typedef enum{
  ASI_DEBIL,//Take away 3 at init
  ASI_DETRI,//Take away 2
  ASI_CON, //Take away 1
  ASI_INIT,//ONCE
  ASI_LVL_EVERY,
  ASI_LVL_COMPOSITE,//11
  ASI_LVL_EVEN,//10
  ASI_LVL_PRIME,//8
  ASI_LVL_SQUARE,//3
  ASI_LVL_CAP,
  ASI_DONE
}AsiEvent;

typedef enum{
  SC_MIN,
  SC_INFER,
  SC_LESSER,
  SC_BELOW,
  SC_AVERAGE,
  SC_ABOVE,
  SC_GREATER,
  SC_SUPER,
  SC_MAX,
  SC_DONE
}StatClassif;

typedef enum{
  RANGE_AGGRO,
  RANGE_LOITER,
  RANGE_NEAR,
  RANGE_ROAM,
  RANGE_EMPTY 
}RangeType;

//SORTED IN APPLICATION ORDER
typedef enum{
  AFF_NONE,
  AFF_BASE,
  AFF_ADD,
  AFF_SUB,
  AFF_MUL,
  AFF_FRACT,
  AFF_DONE
}ValueAffix;

typedef enum{
  MOD_NONE,
  MOD_SQRT,
  MOD_CBRT,
  MOD_NEG_SQRT,
  MOD_ADD,
  MOD_DONE
}ModifierType;

typedef enum{
  VAL_NONE = -1,
  VAL_HIT,
  VAL_ADV_HIT,
  VAL_ADV_DMG,
  VAL_PENN,
  VAL_SAVE,
  VAL_ADV_SAVE,
  VAL_WORTH,
  VAL_WEIGHT,
  VAL_DURI,
  VAL_STORAGE,
  VAL_ALL,
}ValueCategory;

typedef enum{
  STAT_NONE = -1,
  STAT_REACH,
  STAT_DAMAGE,
  STAT_HEALTH,
  STAT_ARMOR,
  STAT_AGGRO,
  STAT_ACTIONS,
  STAT_ENERGY,
  STAT_STAMINA,
  STAT_STAMINA_REGEN,
  STAT_ENERGY_REGEN,
  STAT_STAMINA_REGEN_RATE,
  STAT_ENERGY_REGEN_RATE,
  STAT_RAGE,
  STAT_HEALTH_REGEN,
  STAT_HEALTH_REGEN_RATE,
  STAT_ENDURANCE,
  STAT_WILL,
  STAT_ENT_DONE,
  STAT_TIME,
  STAT_DONE,
}StatType;

typedef enum{
  ATTR_NONE = -1,
  ATTR_CON,
  ATTR_STR,
  ATTR_DEX,
  ATTR_INT,
  ATTR_WIS,
  ATTR_CHAR,
  ATTR_BLANK,
  ATTR_DONE
}AttributeType;

typedef enum{
  DMG_NONE = -1,

  DMG_BLUNT,
  DMG_PIERCE,
  DMG_SLASH,

  DMG_BLEED,
  DMG_FIRE,
  DMG_COLD,
  DMG_LIGHTNING,
  DMG_ACID,
  DMG_POISON,

  DMG_PSYCHIC,
  DMG_RADIANT,
  DMG_NECROTIC,
  DMG_FORCE,
  DMG_TRUE,

  DMG_DONE
}DamageType;

typedef enum{
  STATE_NONE,//if ent_t is properly initalized to {0} this is already set
  STATE_SPAWN,//Should only be set after NONE
  STATE_IDLE, //should be able to move freely between these ==>
  STATE_WANDER,
  STATE_ACTION,
  STATE_AGGRO,
  STATE_ATTACK,
  STATE_STANDBY,
  STATE_SELECTION,
  STATE_DIE,//<===== In MOST cases. Should not be able to go down from DIE
  STATE_DEAD,
  STATE_END//sentinel entity state should never be this or greater
}EntityState;

typedef enum{
  ENT_PERSON,
  ENT_GOBLIN,
  ENT_ORC,
  ENT_OGRE,
  ENT_ORC_FIGHTER,
  ENT_BERSERKER,
  ENT_HOBGOBLIN,
  ENT_OROG,
  ENT_SCORPION,
  ENT_SPIDER,
  ENT_TROLL,
  ENT_TROLL_CAVE,
  ENT_BEAR,
  ENT_WOLF,
  ENT_RAT,
  ENT_DONE
}EntityType;

typedef enum{
  ENV_BONES_BEAST,
  ENV_BOULDER,
  ENV_COBBLE,
  ENV_COBBLE_WORN,
  ENV_FLOWERS,
  ENV_FLOWERS_THIN,
  ENV_FOREST_FIR,
  ENV_GRASS,
  ENV_GRASS_SPARSE,
  ENV_GRASS_WILD,
  ENV_LEAVES,
  ENV_TREE_MAPLE,
  ENV_MEADOW,
  ENV_TREE_OLDGROWTH,
  ENV_TREE_PINE,
  ENV_ROAD,
  ENV_ROAD_CROSS,
  ENV_ROAD_FORK,
  ENV_ROAD_TURN,
  ENV_TREE_BIGLEAF,
  ENV_TREE_CEDAR,
  ENV_TREE_DEAD,
  ENV_TREE_DYING,
  ENV_TREE_FELLED,
  ENV_TREE_FIR,
  ENV_FOREST,
  ENV_WEB,
  ENV_DIRT,
  ENV_DIRT_PATCH,
  ENV_CAMP,
  ENV_FLOOR_DUNGEON,
  ENV_STONE_WALL,
  ENV_WALL_DUNGEON,
  ENV_WALL_RUIN,
  ENV_DOOR_DUNGEON,
  ENV_DOOR_HEAVY,
  ENV_DOOR_VAULT,
  ENV_BORDER_DUNGEON,
  ENV_FURNITURE_CHAIR,
  ENV_DONE
}EnvTile;

typedef enum{
  SIZE_TINY,
  SIZE_SMALL,
  SIZE_MEDIUM,
  SIZE_LARGE,
  SIZE_HUGE,
  SIZE_CAP
}MonsterSize;

typedef enum{
  MOB_HUMANOID,
  MOB_MONSTROUS,
  MOB_BEAST,
  MOB_UNDEAD,
  MOB_CONSTRUCT,
  MOB_DEMONIC,
  MOB_FEY,
  MOB_CIVILIAN,
  MOB_PLAYER,
  MOB_DONE
}MobCategory;

typedef enum{
  SPAWN_NONE,
  SPAWN_PLAYER,
  SPAWN_SOLO,
  SPAWN_PACK,
  SPAWN_SWARM,
  SPAWN_DONE
}SpawnType;

typedef enum{
  ITEM_NONE,
  ITEM_WEAPON,
  ITEM_ARMOR,
  ITEM_CONSUMABLE,
  ITEM_SCROLL,
  ITEM_TOME,
  ITEM_DONE
}ItemCategory;

typedef enum{
  GEAR_NONE,
  GEAR_MACE,
  GEAR_LEATHER_ARMOR,
  GEAR_LEATHER_CAP,
  GEAR_CLUB,
  GEAR_HAND_AXE,
  GEAR_CLOTH_ARMOR,
  GEAR_DAGGER,
  GEAR_BOW_LIGHT,
  GEAR_POT_HEALTH,
  GEAR_PICK,
  GEAR_HAMMER_LIGHT,
  GEAR_DONE
}GearID;

typedef enum{
  ARMOR_NONE,
  ARMOR_NATURAL,
  ARMOR_PADDED,
  ARMOR_LEATHER,
  ARMOR_CHAIN,
  ARMOR_PLATE,
  ARMOR_SHIELD,
  ARMOR_DONE
}ArmorType;

typedef enum{
  WEAP_NONE,
  WEAP_MACE,
  WEAP_SWORD,
  WEAP_AXE,
  WEAP_DAGGER,
  WEAP_BOW,
  WEAP_CROSS_BOW,
  WEAP_POLE_ARM,
  WEAP_STAFF,
  WEAP_PICK,
  WEAP_WHIP,
  WEAP_DART,
  WEAP_SLING,
  WEAP_BLOW,
  WEAP_SICKLE,
  WEAP_DONE
}WeaponType;

typedef enum{
  CONS_NONE = -1,
  CONS_POT,
  CONS_FOOD,
  CONS_DRINK,
  CONS_DONE
}ConsumeType;

typedef enum{
  DARK_FOREST,
  DANK_DUNGEON,
  MAP_DONE,
}MapID;

typedef enum{
  UI_SELECTOR_CHOSEN=1,
  UI_SELECTOR_EMPTY,
  UI_SELECTOR_VALID,
  UI_ALL,
}UiType;

typedef enum{
  ELEMENT_EMPTY,
  UI_DONE = UI_ALL,
  ELEMENT_COUNT
}ElementID;

typedef enum{
  TILE_EMPTY,
  TILE_SUCCESS,
  TILE_ISSUES,
  TILE_COLLISION,
  TILE_OCCUPIED,
  TILE_BORDER,
  TILE_OUT_OF_BOUNDS,
  TILE_ERROR
}TileStatus;

typedef enum{
  ACTION_NONE,
  ACTION_MOVE,
  ACTION_ATTACK,
  ACTION_WEAPON,
  ACTION_ITEM,
  ACTION_MAGIC,
  ACTION_CANTRIP,
  ACTION_PASSIVE,
  ACTION_SAVE,
  ACTION_SLOTTED,
  ACTION_SELECT,
  ACTION_DONE
}ActionType;

typedef enum{
  SLOT_NONE = -1,
  SLOT_ATTACK,
  SLOT_INATE,
  SLOT_ITEM,
  SLOT_SPELL,
  SLOT_SAVE,
  SLOT_ALL
}ActionSlot;

typedef enum{
  ABILITY_NONE,
  ABILITY_WACK,
  ABILITY_BITE,
  ABILITY_CHEW,
  ABILITY_GNAW,
  ABILITY_CLAW,
  ABILITY_SWIPE,
  ABILITY_BITE_POISON,
  ABILITY_POISON,
  ABILITY_MAGIC_MISSLE,
  ABILITY_ELDRITCH_BLAST,
  ABILITY_RESISTANCE,
  ABILITY_SACRED_FLAME,
  ABILITY_STARRY_WISP,
  ABILITY_MAGIC_STONE,
  ABILITY_POISON_SPRAY,
  ABILITY_FIRE_BOLT,
  ABILITY_REND,
  ABILITY_HAMSTRING,
  ABILITY_RAGE,
  ABILITY_WEAP,
  ABILITY_WEAP_BLUDGEON,
  ABILITY_WEAP_CHOP,
  ABILITY_WEAP_STAB,
  ABILITY_WEAP_SLASH,
  ABILITY_WEAP_PIERCE,
  ABILITY_WEAP_RANGE_PIERCE,
  ABILITY_STATUS,
  ABILITY_BLEED,
  ABILITY_ARMOR,
  ABILITY_ARMOR_SAVE,
  ABILITY_ARMOR_DR,
  ABILITY_ITEM,
  ABILITY_ITEM_HEAL,
  ABILITY_DONE,
}AbilityID;

typedef enum {
  AT_NONE = -1,
  AT_HEAL,
  AT_DMG,
  AT_SAVE,
  AT_DR,
  AT_DONE
}AbilityType;

typedef enum{
  DES_NONE,
  DES_FACING,
  DES_SELECT_TARGET,
  DES_MULTI_TARGET,
  DES_AREA,
  DES_SELF,
  DES_DIR,
}DesignationType;

typedef enum{
  BEHAVIOR_NONE,
  BEHAVIOR_CHANGE_STATE,      //1
  BEHAVIOR_GET_TARGET,        //2
  BEHAVIOR_GET_DEST,          //3
  BEHAVIOR_MOVE_TO_TARGET,    //4
  BEHAVIOR_MOVE_TO_DEST,      //4
  BEHAVIOR_CAN_ATTACK,        //5
  BEHAVIOR_ATTACK,            //6
  BEHAVIOR_SEE,               //8
  BEHAVIOR_CHECK_TURN_STATE,  //9
  BEHAVIOR_TAKE_TURN,         //10
  BEHAVIOR_MOVE,              //11
  BEHAVIOR_CHECK_AGGRO,       //12
  BEHAVIOR_ACQUIRE,           //13
  BEHAVIOR_TRY_ATTACK,        //14
  BEHAVIOR_APPROACH,          //15
  BEHAVIOR_WANDER,            //16
  BEHAVIOR_SEEK,              //17
  BEHAVIOR_TAKE_ACTION,       //18
  BEHAVIOR_ACTION,            //19
  BEHAVIOR_NO_ACTION,         //20
  BEHAVIOR_COMBAT,            //21
  BEHAVIOR_MOB_AGGRO,         //22
  BEHAVIOR_STANDBY,           //23
  BEHAVIOR_COUNT
}BehaviorID;

typedef enum{
  IR_NONE,
  IR_FAIL,
  IR_CRITICAL_FAIL,
  IR_SUCCESS,
  IR_TOTAL_SUCC,
  IR_MAX
}InteractResult;

typedef uint64_t event_uid_i;
typedef enum{
  EVENT_GAME_PROCESS,
  EVENT_INTERACTION,
  EVENT_TURN,
  EVENT_PLAY_SFX,
  EVENT_SONG_END,
  EVENT_SONG_FADE_IN,
  EVENT_SONG_FADE_OUT,
  EVENT_WAIT,
  EVENT_SPAWN,
  EVENT_DECAY,
  EVENT_FINISH,
  EVENT_SKILL,
  EVENT_NONE,
  MAX_EVENTS
} EventType;

typedef enum{
  SKILL_NONE,
  SKILL_LVL,
  SKILL_ACRO,
  SKILL_ALCH,
  SKILL_ANIM,
  SKILL_ARCANA,
  SKILL_ARMOR_NATURAL,
  SKILL_ARMOR_PADDED,
  SKILL_ARMOR_LEATHER,
  SKILL_ARMOR_CHAIN,
  SKILL_ARMOR_PLATE,
  SKILL_ARMOR_SHIELD,
  SKILL_ATH,
  SKILL_CALL,
  SKILL_CARP,
  SKILL_CART,
  SKILL_COBB,
  SKILL_COOK,
  SKILL_DECEPT,
  SKILL_GLASS,
  SKILL_HIST,
  SKILL_HERB,
  SKILL_INSIGHT,
  SKILL_INTIM,
  SKILL_INVEST,
  SKILL_JEWL,
  SKILL_LW,
  SKILL_MASON,
  SKILL_MED,
  SKILL_NATURE,
  SKILL_PAINT,
  SKILL_PERCEPT,
  SKILL_PERFORM,
  SKILL_PERSUAD,
  SKILL_POISON,
  SKILL_POTT,
  SKILL_RELIG,
  SKILL_SLEIGHT,
  SKILL_SMITH,
  SKILL_SPELL_ABJ,
  SKILL_SPELL_CONJ,
  SKILL_SPELL_DIV,
  SKILL_SPELL_ENCH,
  SKILL_SPELL_EVO,
  SKILL_SPELL_ILL,
  SKILL_SPELL_NECRO,
  SKILL_SPELL_TRANS,
  SKILL_STEALTH,
  SKILL_STONE,
  SKILL_SURV,
  SKILL_TINK,
  SKILL_TOOL_AXE,
  SKILL_TOOL_HAMMER,
  SKILL_TOOL_PICK,
  SKILL_THEFT,
  SKILL_WEAV,
  SKILL_WEAP_SIMP,
  SKILL_WEAP_MART,
  SKILL_WEAP_MACE,
  SKILL_WEAP_SWORD,
  SKILL_WEAP_AXE,
  SKILL_WEAP_DAGGER,
  SKILL_WEAP_BOW,
  SKILL_WEAP_NONE,
  SKILL_WOOD,
  SKILL_DONE
}SkillType;

typedef enum{
  RATE_NONE,
  RATE_LINEAR,
  RATE_REWARD,
  RATE_REWARD_SLOW,
  RATE_ALL_OR_NOTHING,
  RATE_RISK,
  RATE_RISK_SLOW,
  RATE_DONE
}SkillRate;

typedef enum{
  SOC_NONE,
  SOC_HIVE,
  SOC_FERAL,
  SOC_FAMILY,
  SOC_INSTINCTIVE,
  SOC_PRIMITIVE,
  SOC_MARTIAL,
  SOC_CIVIL,
  SOC_HIGH,
  SOC_DONE
}SocietyType;

#endif
