#ifndef __GAME_ENUM__ 
#define __GAME_ENUM__ 

#define BIT64(n) (1ULL << (n))

#define SKILL_RANGE_WEAP (Cell){SKILL_WEAP_MACE, SKILL_WOOD}
#define TREAT_AGGRO_MASK (TREAT_DEFEND | TREAT_KILL | TREAT_EAT)
#define TREAT_RUN_MASK (TREAT_AVOID | TREAT_FEAR)

typedef enum{
  ACT_NONE,
  ACT_ATTACK,
  ACT_MISS,
  ACT_KILL,
  ACT_END,
  ACT_ALL,
}Activity;

typedef enum{
  OBJ_NONE = -1,
  OBJ_ENT,
  OBJ_ENV,
  OBJ_MAP_CELL,
  //OBJ_ABILITY,
  OBJ_ALL
}ObjectCategory;

typedef enum{
  SCORE_RES,
  SCORE_CR,
  SCORE_PATH,
  SCORE_THREAT,
  SCORE_ALL,
}Score;

typedef enum{
  SATUR_FAINT,
  SATUR_LOW,
  SATUR_SOFT,
  SATUR_MED,
  SATUR_RICH,
  SATUR_STRONG,
  SATUR_MAX
}Saturation;

typedef enum {
  MAG_NONE = -1,
  MAG_MINOR,
  MAG_MODEST,
  MAG_NOMINAL,
  MAG_SIGNIF,
  MAG_DONE
}Magnitude;

typedef enum {
  TREAT_NONE,
  TREAT_KILL,
  TREAT_DEFEND,
  TREAT_EAT,
  TREAT_HELP,
  TREAT_FLEE,
  TREAT_DONE
}Treatment;

typedef enum{
  SCREEN_CTX_TAR,
  SCREEN_CTX_HOVER,
  SCREEN_CTX_ALL
}ScreenContextType;

typedef enum{
  VIS_NEVER = -1,
  VIS_UNSEEN,
  VIS_HAS,
  VIS_EXPLORED,
  VIS_FULL,
  VIS_DONE,
}Visibility;

typedef enum {
  DATA_NONE,
  DATA_INT,
  DATA_FLOAT,
  DATA_BOOL,
  DATA_PTR,
  DATA_CELL,
  DATA_UINT64,
  DATA_GOUID,
  DATA_STRING,
  DATA_ENTITY,
  DATA_ABILITY,
  DATA_DMG,
  DATA_ENV,
  DATA_MAP_CELL,
  DATA_NEED,
  DATA_STAT,
  DATA_SKILL,
  DATA_ITEM,
  DATA_INV,
  DATA_LOCAL_CTX,
} DataType;

typedef enum {
  DEBUG_NONE,
  DEBUG_CELL,
  DEBUG_SHAPE,
  DEBUG_TEXT,
  DEBUG_ALL
}DebugType;

typedef enum{
  STEP_NONE = -1,
  STEP_ACTION,
  STEP_TURN,
  STEP_FRAME,
  STEP_FIXED,
  STEP_IGM,//IN GAME MINUTE
  STEP_IGH,//IN GAME HOUR
  STEP_IGD,// IN GAME DAY
  STEP_DONE
}StepType;

typedef enum{
  ASI_DEBIL,//Take away 3 at init
  ASI_DETRI,//Take away 2
  ASI_CON, //Take away 1
  ASI_INIT,//ONCE
  ASI_LVL_EVERY,
  ASI_LVL_COMPOSITE,//11
  ASI_LVL_EVEN,//10
  ASI_LVL_PRIME,//8
  ASI_LVL_SQUARE,//3
  ASI_LVL_CAP,
  ASI_DONE
}AsiEvent;

typedef enum{
  SC_MIN,
  SC_INFER,
  SC_LESSER,
  SC_BELOW,
  SC_AVERAGE,
  SC_ABOVE,
  SC_GREATER,
  SC_SUPER,
  SC_MAX,
  SC_DONE
}StatClassif;

typedef enum{
  RANGE_AGGRO,
  RANGE_LOITER,
  RANGE_NEAR,
  RANGE_ROAM,
  RANGE_EMPTY 
}RangeType;

//SORTED IN APPLICATION ORDER
typedef enum{
  AFF_NONE,
  AFF_BASE,
  AFF_ADD,
  AFF_SUB,
  AFF_MUL,
  AFF_FRACT,
  AFF_DONE
}ValueAffix;

typedef enum{
  MM_NONE,
  MM_ALPHA,
  MM_BRUTE,
  MM_HYBRID,
  MM_REGION,
  MM_DONE
}MobMod;

typedef enum{
  MOD_NONE,
  MOD_SQRT,
  MOD_CBRT,
  MOD_NEG_SQRT,
  MOD_ADD,
  MOD_DONE
}ModifierType;

typedef enum{
  VAL_NONE = -1,
  VAL_HIT,
  VAL_ADV_HIT,
  VAL_DMG,
  VAL_DMG_BONUS,
  VAL_DMG_DIE,
  VAL_ADV_DMG,
  VAL_PENN,
  VAL_SAVE,
  VAL_ADV_SAVE,
  VAL_REACH,
  VAL_DUR,
  VAL_SWAP_HIT,
  VAL_SWAP_DMG,
  VAL_WORTH,
  VAL_WEIGHT,
  VAL_SIZE,
  VAL_DURI,
  VAL_EXP,
  VAL_QUANT,
  VAL_STORAGE,
  VAL_ALL,
}ValueCategory;

typedef enum{
  STAT_NONE,// = -1,
  STAT_REACH,
  STAT_DAMAGE,
  STAT_HEALTH,
  STAT_ARMOR,
  STAT_ENERGY,
  STAT_STAMINA,
  STAT_STAMINA_REGEN,
  STAT_ENERGY_REGEN,
  STAT_STAMINA_REGEN_RATE,
  STAT_ENERGY_REGEN_RATE,
  STAT_RAGE,
  STAT_HEALTH_REGEN,
  STAT_HEALTH_REGEN_RATE,
  STAT_ENDURANCE,
  STAT_WILL,
  STAT_ENT_DONE,
  STAT_TIME,
  STAT_DONE,
}StatType;

typedef enum{
  SEN_SEE,
  SEN_HEAR,
  SEN_SMELL,
  SEN_DONE
}Senses;

typedef enum{
  N_NONE = -1,
  N_SOC,
  N_SLEEP,
  N_THIRST,
  N_HUNGER,
  N_DONE,
}Needs;

typedef enum{
  NEED_MET = 0,
  NEED_LOW,
  NEED_OK,
  NEED_HIGH,
  NEED_CRITICAL,
  NEED_DONE
} NeedStatus;

typedef enum{
  ATTR_NONE,// = -1,
  ATTR_CON,
  ATTR_STR,
  ATTR_DEX,
  ATTR_INT,
  ATTR_WIS,
  ATTR_CHAR,
  ATTR_BLANK,
  ATTR_DONE
}AttributeType;

typedef enum{
  DMG_NONE = -1,

  DMG_BLUNT,
  DMG_PIERCE,
  DMG_SLASH,

  DMG_BLEED,
  DMG_FIRE,
  DMG_COLD,
  DMG_LIGHTNING,
  DMG_ACID,
  DMG_POISON,

  DMG_PSYCHIC,
  DMG_RADIANT,
  DMG_NECROTIC,
  DMG_FORCE,
  DMG_TRUE,

  DMG_DONE
}DamageType;
typedef enum{
  ENV_STATUS_SPAWN,
  ENV_STATUS_NORMAL,
  ENV_STATUS_DEAD
}EnvStatus;

typedef enum{
  STATE_NONE,//if ent_t is properly initalized to {0} this is already set
  STATE_SPAWN,//Should only be set after NONE
  STATE_IDLE, //should be able to move freely between these ==>
  STATE_ACTION,
  STATE_AGGRO,
  STATE_ATTACK,
  STATE_NEED,
  STATE_SELECTION,
  STATE_DIE,//<===== In MOST cases. Should not be able to go down from DIE
  STATE_DEAD,
  STATE_STANDBY,
  STATE_RETURN,
  STATE_END//sentinel entity state should never be this or greater
}EntityState;

typedef enum{
  ENT_STATUS_NONE,
  ENT_STATUS_SPAWN,
  ENT_STATUS_ALIVE,
  ENT_STATUS_DEAD
}EntityStatus;

typedef enum{
  ENT_NONE = -1,
  ENT_PERSON,
  ENT_GOBLIN,
  ENT_ORC,
  ENT_OGRE,
  ENT_HOBGOBLIN,
  ENT_SCORPION,
  ENT_SPIDER,
  ENT_TROLL,
  ENT_BEAR,
  ENT_WOLF,
  ENT_RAT,
  ENT_SKELETON,
  ENT_DEER,
  ENT_KOBOLD,
  ENT_BUGBEAR,
  ENT_KNIGHT,
  ENT_FOOTMAN,
  ENT_DONE
}EntityType;

typedef enum{
  ENV_BONES_BEAST,
  ENV_BOULDER,
  ENV_COBBLE,
  ENV_COBBLE_WORN,
  ENV_FLOWERS,
  ENV_FLOWERS_THIN,
  ENV_FOREST_FIR,
  ENV_GRASS,
  ENV_GRASS_SPARSE,
  ENV_GRASS_WILD,
  ENV_LEAVES,
  ENV_TREE_MAPLE,
  ENV_MEADOW,
  ENV_TREE_OLDGROWTH,
  ENV_TREE_PINE,
  ENV_ROAD,
  ENV_ROAD_CROSS,
  ENV_ROAD_FORK,
  ENV_ROAD_TURN,
  ENV_TREE_BIGLEAF,
  ENV_TREE_CEDAR,
  ENV_TREE_DEAD,
  ENV_TREE_DYING,
  ENV_TREE_FELLED,
  ENV_TREE_FIR,
  ENV_FOREST,
  ENV_WEB,
  ENV_DIRT,
  ENV_DIRT_PATCH,
  ENV_CAMP,
  ENV_FLOOR_DUNGEON,
  ENV_STONE_WALL,
  ENV_WALL_DUNGEON,
  ENV_WALL_RUIN,
  ENV_DOOR_DUNGEON,
  ENV_DOOR_HEAVY,
  ENV_DOOR_VAULT,
  ENV_BORDER_DUNGEON,
  ENV_FURNITURE_CHAIR,
  ENV_EXIT,
  ENV_DONE
}EnvTile;

typedef enum{
  MOB_HUMANOID,
  MOB_MONSTROUS,
  MOB_BEAST,
  MOB_UNDEAD,
  MOB_CONSTRUCT,
  MOB_DEMONIC,
  MOB_FEY,
  MOB_CIVILIAN,
  MOB_PLAYER,
  MOB_DONE
}MobCategory;

typedef enum{
  MT_NONE = -1,
  MT_PREY,
  MT_PRED,
  MT_CRITTER,
  MT_BUG,
  MT_FACTION,
  MT_MONSTER,
  MT_LOCALS,
  MT_DONE
}MobType;

typedef enum{
  GEAR_NONE = -1,
  GEAR_MACE,
  GEAR_LEATHER_ARMOR,
  GEAR_LEATHER_CAP,
  GEAR_CLUB,
  GEAR_HAND_AXE,
  GEAR_CLOTH_ARMOR,
  GEAR_DAGGER,
  GEAR_BOW_LIGHT,
  GEAR_POT_HEALTH,
  GEAR_PICK,
  GEAR_HAMMER_LIGHT,
  GEAR_BANDOLIER,
  GEAR_DONE
}GearID;

typedef enum{
  ARMOR_NONE,
  ARMOR_NATURAL,
  ARMOR_CLOTH,
  ARMOR_PADDED,
  ARMOR_LEATHER,
  ARMOR_CHAIN,
  ARMOR_PLATE,
  ARMOR_SHIELD,
  ARMOR_DONE
}ArmorType;

typedef enum{
  WEAP_NONE,
  WEAP_MACE,
  WEAP_SWORD,
  WEAP_AXE,
  WEAP_DAGGER,
  WEAP_JAVELIN,
  WEAP_BOW,
  WEAP_CROSS_BOW,
  WEAP_POLE_ARM,
  WEAP_STAFF,
  WEAP_PICK,
  WEAP_WHIP,
  WEAP_DART,
  WEAP_SLING,
  WEAP_NET,
  WEAP_BLOW,
  WEAP_SICKLE,
  WEAP_DONE
}WeaponType;

typedef enum{
  CONS_NONE = -1,
  CONS_POT,
  CONS_FOOD,
  CONS_DRINK,
  CONS_DONE
}ConsumeType;

typedef enum{
  DARK_FOREST,
  DANK_DUNGEON,
  MAP_DONE,
}MapID;

typedef enum{
  BIO_NONE = -1,
  BIO_CAVE,
  BIO_DUNGEON,
  BIO_FOREST,
  BIO_DONE,
}Biome;

typedef enum{
  UI_SELECTOR_CHOSEN=1,
  UI_SELECTOR_EMPTY,
  UI_SELECTOR_VALID,
  UI_GRID_CELL,
  UI_ALL,
}UiType;

typedef enum{
  ELEMENT_EMPTY,
  UI_DONE = UI_ALL,
  ELEMENT_COUNT
}ElementID;

typedef enum{
  TILE_EMPTY,
  TILE_SUCCESS,
  TILE_ISSUES,
  TILE_COLLISION,
  TILE_OCCUPIED,
  TILE_REACHABLE,
  TILE_BORDER,
  TILE_OUT_OF_BOUNDS,
  TILE_ERROR,
  TILE_UNREACHABLE
}TileStatus;

typedef enum{
  ACTION_NONE,
  ACTION_MOVE,
  ACTION_ATTACK,
  ACTION_WEAPON,
  ACTION_ITEM,
  ACTION_MAGIC,
  ACTION_CANTRIP,
  ACTION_INTERACT,
  ACTION_PASSIVE,
  ACTION_SAVE,
  ACTION_SLOTTED,
  ACTION_SELECT,
  ACTION_DONE
}ActionType;

typedef enum{
  ACT_MAIN,
  ACT_BONUS,
  ACT_REACT,
  ACT_DONE
}ActionCategory;

typedef enum{
  TURN_NONE = -1,
  TURN_MAIN,
  TURN_POST,
  TURN_END,
  TURN_ALL,
}TurnPhase;

typedef enum{
  BAT_HIT,
  BAT_DMG,
  BAT_DONE,
}BattleStep;

typedef enum{
  COM_INIT,
  COM_BATTLE,
  COM_RESPONSE,
  COM_END,
}CombatPhase;

typedef enum{
  ACT_STATUS_NONE,
  ACT_STATUS_BUILD,
  ACT_STATUS_QUEUED,
  ACT_STATUS_NEXT,
  ACT_STATUS_RUNNING,
  ACT_STATUS_TAKEN,
  ACT_STATUS_ERROR,
  ACT_STATUS_BLOCK,
  ACT_STATUS_BAD_DATA,
  ACT_STATUS_MISQUEUE,
  ACT_STATUS_FULL,
  ACT_STATUS_BAD_ATTACK,
  ACT_STATUS_INVALID,
  ACT_STATUS_WAIT,
  ACT_STATUS_DONE
}ActionStatus;

typedef enum{
  ACT_PARAM_NONE = -1,
  ACT_PARAM_ABILITY,
  ACT_PARAM_OWNER,
  ACT_PARAM_TAR,
  ACT_PARAM_DEST,
  ACT_PARAM_INTER,
  ACT_PARAM_NEED,
  ACT_PARAM_RES,
  ACT_PARAM_REL,
  ACT_PARAM_STEP,
  ACT_PARAM_ALL,
}ActionParam;

typedef enum{
  PARAM_NONE,
  PARAM_RESOURCE,
  PARAM_AGGRO,
  PARAM_RELATE,
  PARAM_POS,
  PARAM_NEED,
  PARAM_SKILL,
  PARAM_ABILITY,
  PARAM_NAME,
  PARAM_SKILL_LVL,
  PARAM_STAT_HEALTH,
  PARAM_STAT_ARMOR,
  PARAM_STAT_STAMINA,
  PARAM_STAT_ENERGY,
  PARAM_INV_HELD,
  PARAM_INV_WORN,
  PARAM_INV_BELT,
  PARAM_INV_SLING,
  PARAM_ITEM,
  PARAM_ALL,
  PARAM_WEAP_TYPE,
}GameObjectParam;

typedef enum {
  REQ_HAS_ABILITY,
  REQ_HAS_ITEM,
  REQ_SKILL_RANK,   // optional if you want this inside the same system
  REQ_STAT_MIN,
  REQ_ATTR_MIN,
} Requirement;

typedef enum{
  AFF_SKILL,
  AFF_ABI,
  AFF_ATTRI,
  AFF_STAT,
  AFF_RES,
}AffectCategory;

typedef enum{
  AFF_ADD_ABI,
  AFF_ADD_ITEM,
  AFF_ADD_SKILL,
  AFF_MOD_ABI,
  AFF_INC_ATTR,
  AFF_INC_STAT,
  AFF_INC_SKILL,
  AFF_INC_RES,
}AffectType;

typedef enum{
  PRIO_NONE = -1,
  PRIO_NEEDS,
  PRIO_ENGAGE,
  PRIO_FLEE,
  PRIO_HELP,
  PRIO_DONE
}Priorities;

typedef enum{
  I_NONE,
  I_CONSUME,
  I_OPEN,
  I_CLOSE,
  I_FLEE,
  I_KILL,
}Interactive;

typedef enum{
  SLOT_NONE = -1,
  SLOT_ATTACK,
  SLOT_INATE,
  SLOT_ITEM,
  SLOT_SPELL,
  SLOT_SAVE,
  SLOT_ALL
}ActionSlot;

typedef enum{
  ITEM_NONE,
  ITEM_WEAPON,
  ITEM_ARMOR,
  ITEM_CONSUMABLE,
  ITEM_CONTAINER,
  ITEM_SCROLL,
  ITEM_TOME,
  ITEM_AMULET,
  ITEM_RING,
  ITEM_AMMO,
  ITEM_DONE
}ItemCategory;

typedef enum{
  INV_NONE = -1,
  INV_HELD,
  INV_WORN,
  INV_BACK,
  INV_BELT,
  INV_SLING,
  INV_QUIVER,
  INV_PACK,
  INV_POUCH,
  INV_SCROLL_CASE,
  INV_DONE
}ItemSlot;

typedef enum{
  STORE_NONE = -1,
  STORE_CARRY,
  STORE_WORN,
  STORE_HELD,
  STORE_CONTAINER,
  STORE_SPECIAL,
  STORE_DONE
}StorageMethod;

typedef enum{
  CLASS_NONE  = -1,
  CLASS_BASE_BARD   ,
  CLASS_BASE_CLERIC ,
  CLASS_BASE_DRUID  ,
  CLASS_BASE_FIGHTER,
  CLASS_BASE_MONK   ,
  CLASS_BASE_RANGER ,
  CLASS_BASE_ROGUE  ,
  CLASS_BASE_LOCK   ,
  CLASS_BASE_WIZ    ,
  CLASS_BASE_BERZ    ,
  CLASS_BASE_SHAMAN  ,
  CLASS_BASE_DONE   ,
  CLASS_SUB_ASSASSIN,
  CLASS_SUB_BEAST,
  CLASS_SUB_CHAMP   ,
  CLASS_SUB_DEATH   ,
  CLASS_SUB_DUNG    ,
  CLASS_SUB_HEX     ,
  CLASS_SUB_NECRO,
  CLASS_SUB_SEER    ,
  CLASS_SUB_SHOOTER ,
  CLASS_SUB_WARLORD,
  CLASS_SUB_WARMAG,
  CLASS_SUB_HARBINGER,
  CLASS_DONE
}Archetype;


typedef enum{
  ABILITY_NONE,
  ABILITY_PUNCH,
  ABILITY_RAM,
  ABILITY_BITE,
  ABILITY_CHEW,
  ABILITY_GNAW,
  ABILITY_CLAW,
  ABILITY_SWIPE,
  ABILITY_BITE_POISON,
  ABILITY_POISON,
  ABILITY_MAGIC_MISSLE,
  ABILITY_ELDRITCH_BLAST,
  ABILITY_RESISTANCE,
  ABILITY_GUIDING_BOLT,
  ABILITY_SACRED_FLAME,
  ABILITY_STARRY_WISP,
  ABILITY_MAGIC_STONE,
  ABILITY_POISON_SPRAY,
  ABILITY_FIRE_BOLT,
  ABILITY_CURE_WOUNDS,
  ABILITY_REND,
  ABILITY_HAMSTRING,
  ABILITY_RAGE,
  ABILITY_DASH,
  ABILITY_THROW_ROCK,
  ABILITY_WEAP,
  ABILITY_WEAP_BLUDGEON,
  ABILITY_WEAP_CHOP,
  ABILITY_WEAP_STAB,
  ABILITY_WEAP_SLASH,
  ABILITY_WEAP_PIERCE,
  ABILITY_WEAP_RANGE_PIERCE,
  ABILITY_STATUS,
  ABILITY_BLEED,
  ABILITY_ARMOR,
  ABILITY_ARMOR_SAVE,
  ABILITY_ARMOR_DR,
  ABILITY_ITEM,
  ABILITY_ITEM_HEAL,
  ABILITY_DONE,
}AbilityID;

typedef enum{
  AFFECT_NONE = -1,
  AFFECT_WEAP_SAP   = BIT64(0),
}AffectID;
typedef uint64_t Affects;

typedef enum {
  AT_NONE = -1,
  AT_HEAL,
  AT_DMG,
  AT_SAVE,
  AT_DR,
  AT_MOVE,
  AT_DONE
}AbilityType;

typedef enum{
  DES_NONE,
  DES_FACING,
  DES_SEL_TAR,
  DES_MULTI_TAR,
  DES_AREA,
  DES_SELF,
  DES_DIR,
}DesignationType;

typedef enum{
  BN_NONE,
  BN_CHANGE_STATE,      //1
  BN_IDLE,
  BN_WANDER,
  BN_SPAWN,
  BN_PREPARE,
  BN_AGGRO,
  BN_AGGRO_DEC,
  BN_PRIO,
  BN_PRIO_DEC,
  BN_NEED,
  BN_NEED_DEC,
  BN_FILL_NEED,
  BN_LOC_DEC,
  BN_ACTION,
  BN_DEC_EXEC,
  BN_DEC,
  BN_CHECK_RANGE,
  BN_CHECK_ABILITY,
  BN_URGENT,
  BN_COUNT
}BehaviorID;

typedef enum{
  IR_NONE,
  IR_FAIL,
  IR_CRITICAL_FAIL,
  IR_ALMOST,
  IR_SUCCESS,
  IR_TOTAL_SUCC,
  IR_MAX,
  IR_DONE
}InteractResult;

typedef enum{
  IM_NONE = -1,
  IM_AGGR,
  IM_TAR,
  IM_DONE
}InteractMember;

typedef enum{
  IP_NONE,
  IP_OWNER,
  IP_ITEM,
  IP_ABILITY,
  IP_ARMOR,
  IP_ACTION,
  IP_DMG,
  IP_DONE
}InteractParams;

typedef uint64_t event_uid_i;
typedef enum{
  EVENT_NONE,
  SCREEN_EVENT_SELECT,
  SCREEN_EVENTS_DONE,
  EVENT_GAME_PROCESS,
  EVENT_PLAYER_INPUT,
  EVENT_INTERACTION,
  EVENT_TURN,
  EVENT_PLAY_SFX,
  EVENT_SONG_END,
  EVENT_SONG_FADE_IN,
  EVENT_SONG_FADE_OUT,
  EVENT_WAIT,
  EVENT_SPAWN,
  EVENT_DECAY,
  EVENT_FINISH,
  EVENT_SKILL,
  EVENT_ADD_LOCAL_CTX,
  EVENT_DEL_LOCAL_CTX,
  EVENT_UPDATE_LOCAL_CTX,
  EVENT_ENT_DEATH,
  EVENT_ENV_DEATH,
  EVENT_ROLL_HIT,
  EVENT_ROLL_DMG,
  EVENT_DAMAGE_TAKEN,
  EVENT_DAMAGE_DEALT,
  EVENT_AGGRO,
  EVENT_ACT_TAKEN,
  EVENT_ACT_STATUS,
  EVENT_NEED_STATUS,
  EVENT_COMBAT,
  EVENT_ENT_STEP,
  EVENT_ENT_ACTIVITY,
  EVENT_COMBAT_ACTIVITY,
  EVENT_DONE,
  MAX_EVENTS
} EventType;

typedef enum{
  EVS_NONE,
  EVS_KILL
}EventStatus;

typedef enum{
  SKILL_NONE,
  SKILL_LVL,
  SKILL_ACRO,
  SKILL_ALCH,
  SKILL_ANIM,
  SKILL_ARCANA,
  SKILL_ARMOR_NATURAL,
  SKILL_ARMOR_CLOTH,
  SKILL_ARMOR_PADDED,
  SKILL_ARMOR_LEATHER,
  SKILL_ARMOR_CHAIN,
  SKILL_ARMOR_PLATE,
  SKILL_ARMOR_SHIELD,
  SKILL_ATH,
  SKILL_CALL,
  SKILL_CARP,
  SKILL_CART,
  SKILL_COBB,
  SKILL_COOK,
  SKILL_DECEPT,
  SKILL_DUEL,
  SKILL_GLASS,
  SKILL_HIST,
  SKILL_HERB,
  SKILL_INSIGHT,
  SKILL_INTIM,
  SKILL_INVEST,
  SKILL_JEWL,
  SKILL_LW,
  SKILL_MASON,
  SKILL_MED,
  SKILL_NATURE,
  SKILL_PAINT,
  SKILL_PERCEPT,
  SKILL_PERFORM,
  SKILL_PERSUAD,
  SKILL_POISON,
  SKILL_POTT,
  SKILL_RELIG,
  SKILL_SLEIGHT,
  SKILL_SMITH,
  SKILL_SPELL_ABJ,
  SKILL_SPELL_CONJ,
  SKILL_SPELL_DIV,
  SKILL_SPELL_ENCH,
  SKILL_SPELL_EVO,
  SKILL_SPELL_ILL,
  SKILL_SPELL_NECRO,
  SKILL_SPELL_TRANS,
  SKILL_STEALTH,
  SKILL_STONE,
  SKILL_SURV,
  SKILL_TINK,
  SKILL_THEFT,
  SKILL_WEAV,
  SKILL_WEAP_SIMP,
  SKILL_WEAP_MART,
  SKILL_WEAP_MACE,
  SKILL_WEAP_SHOT,
  SKILL_WEAP_SWORD,
  SKILL_WEAP_AXE,
  SKILL_WEAP_DAGGER,
  SKILL_WEAP_BOW,
  SKILL_WEAP_PICK,
  SKILL_WEAP_STAFF,
  SKILL_WEAP_SPEAR,
  SKILL_WEAP_WHIP,
  SKILL_WEAP_NET,
  SKILL_WEAP_GREAT,
  SKILL_WEAP_NONE,
  SKILL_WOOD,
  SKILL_WRESTLE,
  SKILL_DONE
}SkillType;

typedef enum{
  RATE_NONE,
  RATE_LINEAR,
  RATE_REWARD,
  RATE_REWARD_SLOW,
  RATE_ALL_OR_NOTHING,
  RATE_RISK,
  RATE_RISK_SLOW,
  RATE_DONE
}SkillRate;

typedef enum {
  SR_NONE,
  SR_NOVICE,
  SR_SKILLED,
  SR_PROFIC,
  SR_ADEPT,
  SR_EXPERT,
  SR_ACCOMP,
  SR_GREAT,
  SR_ARTIS,
  SR_MASTER,
  SR_MASTER_H,
  SR_MASTER_G,
  SR_LEGEND,
  SR_DONE
}SkillRank;

typedef enum{
  PROF_NONE,
  PROF_SOLDIER,
  PROF_ARCHER,
  PROF_MAGICIAN,
  PROF_MYSTIC,
  PROF_HEALER,
  PROF_LABORER,
  PROF_HAULER,
  PROF_RUNNER,
  PROF_GATHERER,
  PROF_MINER,
  PROF_CHOPPER,
  PROF_TENDER,
  PROF_SCHOLAR,
  PROF_HUNTER,
  PROF_FISHER,
  PROF_BUILDER,
  PROF_COOK,
  PROF_MEDIC,
  PROF_GUARD,
  PROF_SCRIBE,
  PROF_MERCHANT,
  PROF_WOOD,
  PROF_STONE,
  PROF_METAL,
  PROF_FLETCHER,
  PROF_TANNER,
  PROF_TAILOR,
  PROF_TRAPPER,
  PROF_ENGINEER,
  PROF_RESEARCH,
  PROF_ALCHEMIST,
  PROF_ARCHITECT,
  PROF_SURGEON,
  PROF_BOOKS,
  PROF_END
}Profession;

typedef enum{
  SOC_NONE,
  SOC_HIVE,
  SOC_FERAL,
  SOC_FAMILY,
  SOC_INSTINCTIVE,
  SOC_PRIMITIVE,
  SOC_MARTIAL,
  SOC_CIVIL,
  SOC_HIGH,
  SOC_DONE
}SocietyType;

typedef enum{
  ICON_HELM_COM,
  ICON_POT_FULL,
  ICON_MACE_COM,
  ICON_BELT,
  ICON_TUNIC_COM,
  ICON_ALL,
}Icons;
#endif
