#ifndef ROOM_DATA_H
#define ROOM_DATA_H

#define ROOM_WIDTH 774
#define ROOM_HEIGHT 774

#define GRID_WIDTH 3
#define GRID_HEIGHT 3

#define CELL_WIDTH 258
#define CELL_HEIGHT 258

#define ROOM_LEVEL_COUNT 3

static const ObjectInstance room_instances[SHAPE_COUNT] = {
  {SHAPE_NONE} ,
  {SHAPE_GREEN_SQUARE ,1},
  {SHAPE_GREEN_DIAMOND ,1},
  {SHAPE_GREEN_PENTAGON ,1},
  {SHAPE_GREEN_STUD ,1},
  {SHAPE_GREEN_TRIANGLE ,1},
  {SHAPE_GREEN_COMPASS ,1},
  {SHAPE_GREEN_STAR ,1},
  {SHAPE_GREEN_GEM ,1},
  {SHAPE_GREEN_CIRCLE ,1},
  {SHAPE_GREEN_HEART ,1},
  {SHAPE_GRAY_SQUARE ,1},
  {SHAPE_GRAY_DIAMOND ,1},
  {SHAPE_GRAY_PENTAGON ,1},
  {SHAPE_GRAY_STUD ,1},
  {SHAPE_GRAY_TRIANGLE ,1},
  {SHAPE_GRAY_COMPASS ,1},
  {SHAPE_GRAY_STAR ,1},
  {SHAPE_GRAY_GEM ,1},
  {SHAPE_GRAY_CIRCLE ,1},
  {SHAPE_GRAY_HEART ,1},
  {SHAPE_BLUE_SQUARE ,1},
  {SHAPE_BLUE_DIAMOND ,1},
  {SHAPE_BLUE_PENTAGON ,1},
  {SHAPE_BLUE_STUD ,1},
  {SHAPE_BLUE_TRIANGLE ,1},
  {SHAPE_BLUE_COMPASS ,1},
  {SHAPE_BLUE_STAR ,1},
  {SHAPE_BLUE_GEM ,1},
  {SHAPE_BLUE_CIRCLE ,1},
  {SHAPE_BLUE_HEART ,1},
  {SHAPE_RED_SQUARE ,1},
  {SHAPE_RED_DIAMOND ,1},
  {SHAPE_RED_PENTAGON ,1},
  {SHAPE_RED_STUD ,1},
  {SHAPE_RED_TRIANGLE ,1},
  {SHAPE_RED_COMPASS ,1},
  {SHAPE_RED_STAR ,1},
  {SHAPE_RED_GEM ,1},
  {SHAPE_RED_CIRCLE ,1},
  {SHAPE_RED_HEART ,1},
};

static const ObjectInstance BASE_SHAPE = {SHAPE_NONE ,1,{
  [STATE_PLACED]=BEHAVIOR_SHAPE_PLACED,
    [STATE_CALCULATING]=BEHAVIOR_CALCULATE,
    [STATE_SCORE]=BEHAVIOR_NEXT_TURN
}};
static const TileInstance BASE_TILE = {BACKTILE_01 ,{
  [STATE_EMPTY]=BEHAVIOR_SOLVABLE_CHILD ,
    [STATE_SPAWN]=BEHAVIOR_ACQUIRE_CHILD ,
    [STATE_IDLE]=BEHAVIOR_IDLE_TILE ,
    [STATE_CALCULATING]=BEHAVIOR_SCORE_TURN ,
    [STATE_SCORE]= BEHAVIOR_END_TURN
}};

typedef struct {
  BehaviorID           id;
  bool                 is_root;
  BehaviorTreeType     bt_type;
  behavior_tree_node_t *(*func)(behavior_params_t *);
  bool          param_overide;
  EntityState   state;
  TurnState     turn;
  int           num_children;
  BehaviorID   children[5];
} BehaviorData;

static const BehaviorData room_behaviors[BEHAVIOR_COUNT] = {
  {BEHAVIOR_NONE} ,
  {BEHAVIOR_CHANGE_STATE  ,false,BT_LEAF,LeafChangeState,false, STATE_IDLE,0,0,{}},
  {BEHAVIOR_CHANGE_OWNER_STATE  ,false,BT_LEAF,LeafChangeOwnerState,false, STATE_IDLE,0,0,{}},
  {BEHAVIOR_CHANGE_CHILD_STATE  ,false,BT_LEAF,LeafChangeChildState,false, STATE_IDLE,0,0,{}},
  {BEHAVIOR_CLEAR_MATCH_STATE,false,BT_LEAF,LeafClearMatchState,false, STATE_IDLE,0,0,{}},
  {BEHAVIOR_SELECT_SHAPE ,false,BT_LEAF,LeafSelectShape,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_HELPFUL_SHAPE ,false,BT_LEAF,LeafSelectHelpfulShape,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_INIT_CHILD ,false,BT_LEAF,LeafInitChild,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_ACQUIRE_CHILD ,true,BT_SEQUENCE,NULL,true,STATE_IDLE,0,2, {BEHAVIOR_SELECT_SHAPE,BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_SOLVABLE_CHILD ,true,BT_SEQUENCE,NULL,true,STATE_IDLE,0,2, {BEHAVIOR_HELPFUL_SHAPE,BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_CHECK_OTHERS_STATE  ,false,BT_LEAF,LeafCheckOthersState,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_CHECK_CHILD_STATE  ,false,BT_LEAF,LeafCheckChildState,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_CHECK_OWNERS_STATE  ,false,BT_LEAF,LeafCheckOwnersState,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_PROGRESS_WORLD_STATE  ,false,BT_LEAF,LeafProgressWorldState,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_CHECK_WORLD_STATE ,false,BT_LEAF,LeafCheckWorldState,false, STATE_NONE,0,0,{}},
  {BEHAVIOR_SHAPE_PLACED ,true,BT_SEQUENCE,NULL,true,STATE_CALCULATING,TURN_CALC,3, {BEHAVIOR_CHECK_OTHERS_STATE,BEHAVIOR_CHANGE_STATE,BEHAVIOR_PROGRESS_WORLD_STATE}},
  {BEHAVIOR_START_CALC ,false,BT_SEQUENCE,NULL,true,0,TURN_CALC,1, {BEHAVIOR_CHECK_WORLD_STATE}},
  {BEHAVIOR_MATCH_NEIGHBORS  ,false, BT_LEAF, LeafMatchNeighbors ,NULL,false,0,0,{}},
  {BEHAVIOR_STANDBY ,false,BT_SEQUENCE,NULL,true,STATE_IDLE,0,1,{BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_DEPOSIT_POINTS  ,false,BT_SEQUENCE, NULL, true, STATE_SCORE,0,2,{BEHAVIOR_MATCH_NEIGHBORS, BEHAVIOR_CHANGE_STATE}}, 
  {BEHAVIOR_MATCH_GRID ,false,BT_SELECTOR,NULL,false,0,TURN_SCORE,2, {BEHAVIOR_DEPOSIT_POINTS,BEHAVIOR_STANDBY}},
  {BEHAVIOR_CALC_TILE ,false,BT_SEQUENCE,NULL,true,STATE_CALCULATING,0,1, {BEHAVIOR_CHANGE_OWNER_STATE}},
  {BEHAVIOR_CALCULATE ,true,BT_SEQUENCE,NULL,false,0,0,3, {BEHAVIOR_START_CALC,BEHAVIOR_MATCH_GRID, BEHAVIOR_CALC_TILE}},
  {BEHAVIOR_SCORE_TURN  , true, BT_SEQUENCE,NULL,true,STATE_SCORE,0,3,{BEHAVIOR_CHECK_OWNERS_STATE,BEHAVIOR_MATCH_CHILDREN, BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_MATCH_CHILDREN  ,false, BT_LEAF, LeafMatchChild ,NULL,false,0,0,{}},
  {BEHAVIOR_END_TURN ,true,BT_SEQUENCE,NULL,true,STATE_SCORE,TURN_SCORE,2,{BEHAVIOR_CHECK_OTHERS_STATE,BEHAVIOR_PROGRESS_WORLD_STATE}},
  {BEHAVIOR_IDLE_TILE ,true,BT_SEQUENCE,NULL,true,STATE_CALCULATING,TURN_CALC,2,{BEHAVIOR_CHECK_WORLD_STATE,BEHAVIOR_CHANGE_CHILD_STATE}},
  {BEHAVIOR_CHECK_TURN  ,true,BT_SEQUENCE,NULL,true,STATE_CALCULATING,TURN_CALC,3,{BEHAVIOR_CHECK_WORLD_STATE,BEHAVIOR_CHANGE_OWNER_STATE, BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_NEXT_TURN ,true ,BT_SEQUENCE ,NULL ,true ,STATE_IDLE ,TURN_END ,4 ,{BEHAVIOR_CHECK_WORLD_STATE ,BEHAVIOR_CLEAR_MATCH_STATE, BEHAVIOR_CHANGE_OWNER_STATE, BEHAVIOR_CHANGE_STATE}},
};
#endif
