#ifndef ROOM_DATA_H
#define ROOM_DATA_H

#define ROOM_WIDTH 1080
#define ROOM_HEIGHT 1080

#define ROOM_LEVEL_COUNT 3

static room_gen_t ROOM_TEMPLATES[14]={
  {8, 0,
    ROOM_SIZE_XL | ROOM_LAYOUT_OPEN | ROOM_PURPOSE_LAIR |
      ROOM_SHAPE_SQUARE | ROOM_PLACING_W},
  {
    10, 1,
    ROOM_LAYOUT_HALL | ROOM_SIZE_MASSIVE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_N,{&ROOM_TEMPLATES[0]}
  },
  {10, 1,
    ROOM_LAYOUT_HALL | ROOM_SIZE_MASSIVE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_S,
    {&ROOM_TEMPLATES[4]}
  },
  {8, 2,
    ROOM_LAYOUT_HALL | ROOM_SIZE_HUGE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_HOR | ROOM_PLACING_E,{&ROOM_TEMPLATES[1],&ROOM_TEMPLATES[2]}
  },
  {10,0,
      ROOM_LAYOUT_OPEN | ROOM_SIZE_HUGE | ROOM_PURPOSE_CHALLENGE |
      ROOM_SHAPE_RECT | ROOM_PLACING_S | ROOM_ORIENT_VER
  },
  {5, 0 ,
    ROOM_LAYOUT_OPEN | ROOM_SIZE_HUGE | ROOM_PURPOSE_CONNECT | 
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_HOR | ROOM_PLACING_E,
  },
  {5, 1,
    ROOM_LAYOUT_OPEN | ROOM_SIZE_HUGE | ROOM_PURPOSE_CHALLENGE |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_S,
    {&ROOM_TEMPLATES[9]}
  },
  {7, 1,
    ROOM_LAYOUT_OPEN | ROOM_SIZE_MASSIVE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_N,
    {&ROOM_TEMPLATES[8]}
  },
  {5, 0,
    ROOM_LAYOUT_OPEN | ROOM_SIZE_MAX | ROOM_PURPOSE_CAMP |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_W
  },
  {2, 1,
    ROOM_LAYOUT_ROOM | ROOM_SIZE_MEDIUM | ROOM_PURPOSE_EXIT |
      ROOM_SHAPE_RECT | ROOM_ORIENT_HOR | ROOM_PLACING_S,
    {&ROOM_TEMPLATES[10]}},
  {2, 0,
    ROOM_LAYOUT_ROOM | ROOM_SIZE_MEDIUM | ROOM_PURPOSE_SPAWN |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_HOR | ROOM_PLACING_E}
};

static map_gen_t MAPS[MAP_DONE]= {
  {DARK_FOREST, BIO_FOREST, 1.75, 0.25f,
    MAPFLAG_FOREST, 1, 5, 16, TILEFLAG_FLOOR,
    .mobs = {
      MOB_LOC_FOREST | MOB_FREQ_COMMON |
      MOB_THEME_CRITTER | MOB_THEME_PRIMITIVE | MOB_THEME_PRED | MOB_THEME_GAME | 
      MOB_GROUPING_MASK | MOB_MOD_MASK | MOB_SPAWN_MASK
    },
    2,
    {
      4, 4,
      ROOM_SIZE_HUGE | ROOM_LAYOUT_OPEN | ROOM_PLACING_E |
        ROOM_PURPOSE_START | ROOM_SHAPE_SQUARE,
      {&ROOM_TEMPLATES[5],&ROOM_TEMPLATES[6],&ROOM_TEMPLATES[7],&ROOM_TEMPLATES[0]}
    },
    MN_GRID,
  
  },
  {DANK_DUNGEON, BIO_DUNGEON, 0.75,2.0f,
    MAPFLAG_DUNGEON, 2,20,36, TILEFLAG_DOOR,
    .mobs={
      MOB_LOC_DUNGEON |
        MOB_FREQ_COMMON |
        MOB_MOD_ENLARGE | MOB_MOD_WEAPON | MOB_MOD_ARMOR |
        MOB_THEME_CRITTER | MOB_THEME_PRIMITIVE | MOB_THEME_MARTIAL |
        MOB_GROUPING_SOLO | MOB_GROUPING_PAIRS | MOB_GROUPING_TROOP | MOB_GROUPING_CREW | MOB_GROUPING_SWARM
    },
    1,
    {
      4, 1,
      ROOM_SIZE_LARGE | ROOM_LAYOUT_ROOM | ROOM_PLACING_E |
        ROOM_PURPOSE_START | ROOM_SHAPE_SQUARE,
      {&ROOM_TEMPLATES[3]}
    },
    MN_GRID,
  }
};

static map_node_data_t room_nodes[MAP_NODE_DONE] = {
  {MN_GRID, MAP_NODE_ROOT,NULL,6,{MN_ANCHORS,MN_GRAPH,MN_GRID_GEN,MN_BUILD, MN_DETAIL, MN_CHECK_MAP}},
  {MN_ANCHORS, MAP_NODE_SEQUENCE,NULL,2,{MN_GENERATE_ROOMS,MN_LAYOUT }},
  {MN_GENERATE_ROOMS, MAP_NODE_LEAF, LeafMapGenerateRooms ,0},
  {MN_GRID_GEN, MAP_NODE_SEQUENCE, NULL,3,{MN_APPLY_NODES, MN_COMPUTE_BOUNDS,MN_ALLOCATE_TILES,}},
  {MN_LAYOUT, MAP_NODE_LEAF, LeafMapGridLayout ,0},
  {MN_APPLY_SHAPES,MAP_NODE_LEAF, LeafMapApplyRoomShapes,0},
  {MN_PLACE_ROOMS, MAP_NODE_LEAF, LeafMapPlaceSubrooms,0}, 
  {MN_COMPUTE_BOUNDS, MAP_NODE_LEAF, LeafMapComputeBounds,0}, 
  {MN_ALLOCATE_TILES, MAP_NODE_LEAF, LeafMapAllocateTiles,0}, 
  {MN_CARVE_TILES, MAP_NODE_LEAF, LeafMapCarveTiles,0},
  {MN_GRAPH_ROOTS, MAP_NODE_LEAF, LeafMapGraphNodes,0},
  {MN_BUILD, MAP_NODE_SEQUENCE, NULL, 1,{MN_CARVE_TILES }}, 
  {MN_DETAIL, MAP_NODE_SEQUENCE, NULL, 5,{MN_ECO, MN_ENCASE_FLOORS, MN_PLACE_POI,MN_ENH, MN_SET_PLAYER}},
  {MN_ENCASE_FLOORS, MAP_NODE_LEAF, LeafMapFillWalls,0},
  {MN_PLACE_POI, MAP_NODE_SEQUENCE, NULL,1,{MN_PLACE_SPAWNS}},
  {MN_SET_PLAYER, MAP_NODE_LEAF, LeafMapPlayerSpawn,0},
  {MN_PLACE_SPAWNS, MAP_NODE_LEAF, LeafMapPlaceSpawns,0},
  {MN_ALIGN_ROOMS, MAP_NODE_LEAF, LeafMapAlignNodes,0},
  {MN_CLEANUP, MAP_NODE_SEQUENCE, NULL, 1,{MN_ALIGN_ROOMS,}},
  {MN_APPLY_NODES, MAP_NODE_LEAF, LeafMapNodesToGrid,0},
  {MN_PATHS, MAP_NODE_LEAF, LeafMapCheckPaths,0},
  {MN_CHECK_MAP, MAP_NODE_SEQUENCE, NULL, 3,{MN_PATHS, MN_ISSUES, MN_FIX}},
  {MN_ISSUES, MAP_NODE_LEAF, LeafMapFixIssues, 0},
  {MN_GRAPH, MAP_NODE_SEQUENCE, NULL, 1, { MN_GRAPH_ROOTS}},
  {MN_FIX, MAP_NODE_LEAF, LeafMapApplyFixes,0},
  {MN_ECO, MAP_NODE_LEAF, LeafMapBuildBiome,0},
  {MN_ENH, MAP_NODE_LEAF, LeafMapEnhance,0},
};

static const ItemInstance room_items[GEAR_DONE] = {
  {GEAR_MACE, ITEM_WEAPON, WEAP_MACE,PROP_QUAL_TRASH, PROP_WEAP_SIMP, RAYWHITE, ICON_MACE_COM},
  {GEAR_LEATHER_ARMOR,ITEM_ARMOR,ARMOR_LEATHER,PROP_QUAL_POOR, PROP_WEAP_SIMP, BROWN, ICON_TUNIC_COM},
  {GEAR_LEATHER_CAP, ITEM_ARMOR,ARMOR_LEATHER,PROP_QUAL_STANDARD, PROP_WEAP_SIMP, BROWN, ICON_HELM_COM},
  {GEAR_CLUB, ITEM_WEAPON, WEAP_MACE,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_HAND_AXE, ITEM_WEAPON, WEAP_AXE,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_CLOTH_ARMOR,ITEM_ARMOR,ARMOR_PADDED,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_DAGGER, ITEM_WEAPON, WEAP_DAGGER,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_BOW_LIGHT,ITEM_WEAPON, WEAP_BOW,PROP_QUAL_STANDARD, PROP_WEAP_SIMP},
  {GEAR_POT_HEALTH, ITEM_CONSUMABLE, CONS_POT, PROP_QUAL_POOR, PROP_CONS_HEAL, RED, ICON_POT_FULL},
  {GEAR_PICK, ITEM_WEAPON, WEAP_PICK, PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_HAMMER_LIGHT, ITEM_WEAPON, WEAP_MACE,PROP_QUAL_TRASH, PROP_WEAP_LIGHT | PROP_WEAP_THROW},
  {GEAR_BANDOLIER, ITEM_CONTAINER, INV_SLING, PROP_QUAL_FINE | PROP_MAT_LEATHER, PROP_CONT_PHIAL, BROWN, ICON_BELT}
};

typedef struct {
  BehaviorID           id;
  bool                 is_root;
  BehaviorTreeType     bt_type;
  behavior_tree_node_t *(*func)(behavior_params_t *);
  bool          param_overide;
  EntityState   state;
  int           num_children;
  BehaviorID   children[5];
} BehaviorData;

static const BehaviorData room_behaviors[ BN_COUNT] = {
  {BN_NONE},
  {BN_CHANGE_STATE ,false,BT_LEAF,LeafChangeState},
  {BN_IDLE, true, BT_SELECTOR, NULL, true, STATE_NONE, 2,
    {BN_PRIO, BN_WANDER}},
  {BN_WANDER, false, BT_SEQUENCE, NULL, false, 0, 2,
    {BN_LOC_DEC, BN_DEC}},
  {BN_SPAWN, true, BT_SEQUENCE,  NULL, true, STATE_IDLE, 2, { BN_PREPARE, BN_CHANGE_STATE}},
  {BN_PREPARE, false, BT_LEAF, LeafCheckReady},
  {BN_AGGRO, true, BT_SEQUENCE, NULL, true, STATE_IDLE, 3, 
    {BN_AGGRO_DEC, BN_CHECK_ABILITY, BN_DEC}},
  {BN_AGGRO_DEC, false, BT_LEAF, LeafCheckAggro},
  {BN_PRIO, true, BT_SEQUENCE, NULL, false, 0, 2,
    {BN_PRIO_DEC, BN_CHANGE_STATE}},
  {BN_PRIO_DEC, false, BT_LEAF, LeafGetPriority},
  {BN_NEED, true, BT_SELECTOR, NULL, true, STATE_IDLE, 2,
    {BN_NEED_DEC, BN_CHANGE_STATE}},
  {BN_NEED_DEC, false, BT_SEQUENCE, NULL, false, 0, 3,
    {BN_URGENT, BN_FILL_NEED, BN_DEC}},
  {BN_FILL_NEED, false, BT_LEAF, LeafFillNeed},
  {BN_LOC_DEC, false, BT_LEAF, LeafAcquireDestination},
  {BN_ACTION, false, BT_LEAF, LeafActionDecision},
  {BN_DEC_EXEC, false, BT_LEAF, LeafExecuteDecision},
  {BN_DEC, false, BT_SEQUENCE, NULL, true, STATE_NONE, 3,
    {BN_CHECK_RANGE, BN_DEC_EXEC, BN_CHANGE_STATE}},
  {BN_CHECK_RANGE, false, BT_LEAF, LeafCheckRange},
  {BN_CHECK_ABILITY, false, BT_LEAF, LeafCheckAbility},
  {BN_URGENT, false, BT_LEAF, LeafCheckUrgency},
};
#endif
