#ifndef ROOM_DATA_H
#define ROOM_DATA_H

#define ROOM_WIDTH 774
#define ROOM_HEIGHT 774

#define ROOM_LEVEL_COUNT 3

static room_gen_t ROOM_TEMPLATES[5]={
  {8, 0,
    ROOM_SIZE_XL | ROOM_LAYOUT_OPEN | ROOM_PURPOSE_LAIR |
      ROOM_SHAPE_SQUARE | ROOM_PLACING_W},
  {
    10, 1,
    ROOM_LAYOUT_HALL | ROOM_SIZE_MASSIVE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_N,{&ROOM_TEMPLATES[0]}
  },
  {10, 1,
    ROOM_LAYOUT_HALL | ROOM_SIZE_MASSIVE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_VER | ROOM_PLACING_S,
    {&ROOM_TEMPLATES[4]}
  },
  {8, 2,
    ROOM_LAYOUT_HALL | ROOM_SIZE_HUGE | ROOM_PURPOSE_CONNECT |
      ROOM_SHAPE_SQUARE | ROOM_ORIENT_HOR | ROOM_PLACING_E,{&ROOM_TEMPLATES[1],&ROOM_TEMPLATES[2]}
  },
  {10,0,
      ROOM_LAYOUT_OPEN | ROOM_SIZE_HUGE | ROOM_PURPOSE_CHALLENGE |
      ROOM_SHAPE_RECT | ROOM_PLACING_S | ROOM_ORIENT_VER
  }
};

static map_gen_t MAPS[MAP_DONE]= {
  {DARK_FOREST, MAPFLAG_FOREST},
  {DANK_DUNGEON, MAPFLAG_DUNGEON, 2,20,36,6,
    .mobs={
      MOB_LOC_DUNGEON |
        MOB_FREQ_COMMON |
        MOB_MOD_ENLARGE | MOB_MOD_WEAPON | MOB_MOD_ARMOR |
        MOB_THEME_CRITTER | MOB_THEME_PRIMITIVE | MOB_THEME_MARTIAL |
        MOB_GROUPING_SOLO | MOB_GROUPING_PAIRS|MOB_GROUPING_TROOP | MOB_GROUPING_CREW | MOB_GROUPING_SWARM
    },
    1,
    {
      4, 1,
      ROOM_SIZE_LARGE | ROOM_LAYOUT_ROOM | ROOM_PLACING_E |
        ROOM_PURPOSE_START | ROOM_SHAPE_SQUARE,
      {&ROOM_TEMPLATES[3]}
    },
    MN_GRID,
  }
};

static map_node_data_t room_nodes[MAP_NODE_DONE] = {
  {MN_GRID, MAP_NODE_ROOT,NULL,6,{MN_ANCHORS,MN_GRAPH,MN_GRID_GEN,MN_BUILD, MN_DETAIL, MN_CHECK_MAP}},
  {MN_ANCHORS, MAP_NODE_SEQUENCE,NULL,2,{MN_GENERATE_ROOMS,MN_LAYOUT }},
  {MN_GENERATE_ROOMS, MAP_NODE_LEAF, LeafMapGenerateRooms ,0},
  {MN_GRID_GEN, MAP_NODE_SEQUENCE, NULL,3,{MN_APPLY_NODES, MN_COMPUTE_BOUNDS,MN_ALLOCATE_TILES,}},
  {MN_LAYOUT, MAP_NODE_LEAF, LeafMapGridLayout ,0},
  {MN_APPLY_SHAPES,MAP_NODE_LEAF, LeafMapApplyRoomShapes,0},
  {MN_PLACE_ROOMS, MAP_NODE_LEAF, LeafMapPlaceSubrooms,0}, 
  {MN_COMPUTE_BOUNDS, MAP_NODE_LEAF, LeafMapComputeBounds,0}, 
  {MN_ALLOCATE_TILES, MAP_NODE_LEAF, LeafMapAllocateTiles,0}, 
  {MN_CARVE_TILES, MAP_NODE_LEAF, LeafMapCarveTiles,0},
  {MN_GRAPH_ROOTS, MAP_NODE_LEAF, LeafMapGraphNodes,0},
  {MN_BUILD, MAP_NODE_SEQUENCE, NULL, 1,{MN_CARVE_TILES }}, 
  {MN_DETAIL, MAP_NODE_SEQUENCE, NULL, 3,{MN_ENCASE_FLOORS, MN_PLACE_POI,MN_SET_PLAYER}},
  {MN_ENCASE_FLOORS, MAP_NODE_LEAF, LeafMapFillWalls,0},
  {MN_PLACE_POI, MAP_NODE_SEQUENCE, NULL,1,{MN_PLACE_SPAWNS}},
  {MN_SET_PLAYER, MAP_NODE_LEAF, LeafMapPlayerSpawn,0},
  {MN_PLACE_SPAWNS, MAP_NODE_LEAF, LeafMapPlaceSpawns,0},
  {MN_ALIGN_ROOMS, MAP_NODE_LEAF, LeafMapAlignNodes,0},
  {MN_CLEANUP, MAP_NODE_SEQUENCE, NULL, 1,{MN_ALIGN_ROOMS,}},
  {MN_APPLY_NODES, MAP_NODE_LEAF, LeafMapNodesToGrid,0},
  {MN_PATHS, MAP_NODE_LEAF, LeafMapCheckPaths,0},
  {MN_CHECK_MAP, MAP_NODE_SEQUENCE, NULL, 3,{MN_PATHS, MN_ISSUES, MN_FIX}},
  {MN_ISSUES, MAP_NODE_LEAF, LeafMapFixIssues, 0},
  {MN_GRAPH, MAP_NODE_SEQUENCE, NULL, 1, { MN_GRAPH_ROOTS}},
  {MN_FIX, MAP_NODE_LEAF, LeafMapApplyFixes,0},
};

static const ItemInstance room_items[GEAR_DONE] = {
  {GEAR_MACE, ITEM_WEAPON, WEAP_MACE,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_LEATHER_ARMOR,ITEM_ARMOR,ARMOR_LEATHER,PROP_QUAL_STANDARD, PROP_WEAP_SIMP},
  {GEAR_LEATHER_CAP, ITEM_ARMOR,ARMOR_LEATHER,PROP_QUAL_STANDARD, PROP_WEAP_SIMP},
  {GEAR_CLUB, ITEM_WEAPON, WEAP_MACE,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_HAND_AXE, ITEM_WEAPON, WEAP_AXE,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_CLOTH_ARMOR,ITEM_ARMOR,ARMOR_PADDED,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_DAGGER, ITEM_WEAPON, WEAP_DAGGER,PROP_QUAL_TRASH, PROP_WEAP_SIMP},
  {GEAR_BOW_LIGHT,ITEM_WEAPON, WEAP_BOW,PROP_QUAL_STANDARD, PROP_WEAP_SIMP},
  {GEAR_POT_HEALTH, ITEM_CONSUMABLE, CONS_POT, PROP_QUAL_POOR, PROP_CONS_HEAL}
};

typedef struct {
  BehaviorID           id;
  bool                 is_root;
  BehaviorTreeType     bt_type;
  behavior_tree_node_t *(*func)(behavior_params_t *);
  bool          param_overide;
  EntityState   state;
  int           num_children;
  BehaviorID   children[5];
} BehaviorData;

static const BehaviorData room_behaviors[ BEHAVIOR_COUNT] = {
  { BEHAVIOR_NONE},
  { BEHAVIOR_CHANGE_STATE ,false,BT_LEAF,LeafChangeState,false, STATE_IDLE,0,{}},
  { BEHAVIOR_GET_TARGET ,false,BT_LEAF,LeafAcquireTarget,false, STATE_IDLE,0,{}},
  { BEHAVIOR_GET_DEST,false,BT_LEAF,LeafAcquireDestination,false, STATE_NONE,0,{}},
  { BEHAVIOR_MOVE_TO_TARGET ,false,BT_LEAF,LeafMoveToTarget,false, STATE_IDLE,0,{}},
  { BEHAVIOR_MOVE_TO_DEST,false,BT_LEAF,LeafMoveToDestination,false, STATE_NONE,0,{}},
  {BEHAVIOR_CAN_ATTACK,false,BT_LEAF,LeafCanAttackTarget,false, STATE_NONE,0,{}},
  {BEHAVIOR_ATTACK,false,BT_LEAF,LeafAttackTarget,false, STATE_NONE,0,{}},
  {BEHAVIOR_SEE,false,BT_LEAF,LeafCanSeeTarget,false, STATE_NONE,0,{}},
  {BEHAVIOR_CHECK_TURN_STATE,false, BT_LEAF,LeafCheckTurn,false,0,0,{}},
  {BEHAVIOR_TAKE_TURN,false, BT_LEAF,LeafTakeTurn,false,0,0,{}},
  { BEHAVIOR_MOVE,false,BT_SEQUENCE, NULL,true, STATE_ACTION,3,{ BEHAVIOR_GET_DEST, BEHAVIOR_MOVE_TO_DEST,BEHAVIOR_CHANGE_STATE}},
  { BEHAVIOR_CHECK_AGGRO,false,BT_SEQUENCE, NULL,true, STATE_IDLE,2,{ BEHAVIOR_GET_TARGET, BEHAVIOR_CHANGE_STATE}},
  { BEHAVIOR_ACQUIRE,false, BT_SEQUENCE, NULL,true, STATE_AGGRO,2,{ BEHAVIOR_GET_TARGET, BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_TRY_ATTACK, false, BT_SEQUENCE,NULL,true, STATE_ATTACK,4,{BEHAVIOR_GET_TARGET,BEHAVIOR_SEE,BEHAVIOR_CAN_ATTACK,BEHAVIOR_CHANGE_STATE}},
  {BEHAVIOR_APPROACH , false,BT_SEQUENCE, NULL,false, STATE_NONE,2,{BEHAVIOR_MOVE_TO_TARGET,BEHAVIOR_TAKE_TURN}},
  { BEHAVIOR_WANDER,true,BT_SELECTOR, NULL,false, STATE_NONE,2,{ BEHAVIOR_CHECK_AGGRO, BEHAVIOR_MOVE}},
  { BEHAVIOR_SEEK, true,BT_SELECTOR,NULL,true,STATE_WANDER,2,{ BEHAVIOR_ACQUIRE,  BEHAVIOR_CHANGE_STATE}},
  { BEHAVIOR_TAKE_ACTION,true,BT_SEQUENCE,NULL,false,0,2,{ BEHAVIOR_CHECK_TURN_STATE, BEHAVIOR_TAKE_TURN}},
  { BEHAVIOR_ACTION,false,BT_SELECTOR,NULL,false,0,2,{ BEHAVIOR_TRY_ATTACK, BEHAVIOR_APPROACH}},
  { BEHAVIOR_NO_ACTION, false, BT_SEQUENCE, NULL,true, STATE_IDLE,1,{BEHAVIOR_CHANGE_STATE}},
  { BEHAVIOR_COMBAT ,true,BT_SEQUENCE,NULL,true, STATE_ACTION,2,{ BEHAVIOR_ATTACK, BEHAVIOR_CHANGE_STATE}},
  { BEHAVIOR_MOB_AGGRO ,true,BT_SELECTOR,NULL,false, 0,2,{ BEHAVIOR_ACTION, BEHAVIOR_NO_ACTION}},
};
#endif
